### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by USLTD** [spookybear0/macros.py#1]
Why the hell did you create this **REDACTED** library?!

**Comment by spookybear0** [comment]
for fun :). i have a version with even more stupid features that i forgot to release, i'll update the repository with it.

**Comment by USLTD** [comment]
This is 3rd cursed Python project that I encountered

**Comment by spookybear0** [comment]
1st is ZeroIntensity right?

**Comment by USLTD** [comment]
Yes, his [pointers.py](https://github.com/ZeroIntensity/pointers.py). And second is @clarete's [Forbidden Fruit](https://github.com/clarete/forbiddenfruit)
